require('dotenv').config({quiet:true});
const test=require('node:test');
const assert=require('node:assert/strict');
const {MongoClient}=require('mongodb');
const {randomUUID}=require('node:crypto');
const {createOffers}=require('../offers');
test('offers use authoritative prices, alternate counters, enforce participants and seller-only airport codes and optional refresh requests',{skip:!process.env.MONGO_URI},async()=>{
 const client=await new MongoClient(process.env.MONGO_URI).connect();
 const db=client.db('nextazon_offer_test_'+randomUUID().replaceAll('-',''));
 const events=[];
 const command=createOffers(db,(members,event)=>events.push({members,event}),Error);
 const buyer={accountId:'buyer',username:'Buyer'},seller={accountId:'seller',username:'Seller'},other={accountId:'other'};
 try {
  await db.collection('users').insertMany([{_id:'buyer'},{_id:'seller'},{_id:'other'}]);
  await db.collection('listings').insertOne({_id:'listing',name:'Chair',userId:'seller',price:100,currency:'Bells'});
  await db.collection('catalog').insertOne({_id:'item',name:'Pear',variant:'Original'});
  const input={action:'offer.create',listingId:'listing',buy:true,terms:{kind:'price',amount:1,currency:'Bells'},requestId:randomUUID()};
  let message=await command(buyer,input);
  assert.equal(message.offer.terms.amount,100);
  assert.equal((await command(buyer,input))._id,message._id);
  assert.equal(await db.collection('messages').countDocuments({}),1);
  const act=(user,action,extra={})=>command(user,{action,messageId:message._id,version:message.offer.version,...extra});
  await assert.rejects(act(buyer,'offer.accept'));
  await assert.rejects(act(other,'offer.accept'));
  await assert.rejects(act(seller,'offer.code',{code:'ABCDE'}));
  message=await act(seller,'offer.counter',{terms:{kind:'price',amount:2,currency:'Nook Miles Tickets'}});
  assert.equal(message.offer.recipientId,'buyer');
  await assert.rejects(act(seller,'offer.accept'));
  await assert.rejects(command(buyer,{action:'offer.accept',messageId:message._id,version:1}));
  const concurrent=await Promise.allSettled([act(buyer,'offer.accept'),act(buyer,'offer.accept')]);
  assert.equal(concurrent.filter(result=>result.status==='fulfilled').length,1);
  message=concurrent.find(result=>result.status==='fulfilled').value;
  assert.equal(message.offer.hostId,'seller');
  await assert.rejects(act(buyer,'offer.code',{code:'ABCDE'}));
  await assert.rejects(act(seller,'offer.code',{code:'X'}));
  const now=Date.now();
  message=await act(seller,'offer.code',{code:'abc12'});
  assert.equal(message.offer.dodoCode,'ABC12');
  assert.ok(Date.parse(message.offer.codeRequestAvailableAt)>=now+120000);
  assert.ok(Date.parse(message.offer.codeRequestAvailableAt)<=Date.now()+120000);
  assert.ok(!message.text.includes('ABC12'));
  assert.equal((await command(buyer,{action:'offer.list',conversationId:message.conversationId}))[0].offer.dodoCode,'ABC12');
  await assert.rejects(command(other,{action:'offer.list',conversationId:message.conversationId}));
  await assert.rejects(act(buyer,'offer.requestCode'));
  await db.collection('messages').updateOne({_id:message._id},{$set:{'offer.codeRequestAvailableAt':new Date(Date.now()-1).toISOString()}});
  await assert.rejects(act(seller,'offer.requestCode'));
  message=await act(buyer,'offer.requestCode');
  assert.equal(message.offer.codeRequested,true);
  assert.equal(message.offer.dodoCode,'ABC12');
  await assert.rejects(act(buyer,'offer.requestCode'));
  message=await act(seller,'offer.code',{code:'xyz99'});
  assert.equal(message.offer.codeRequested,false);
  assert.equal(message.offer.dodoCode,'XYZ99');
  assert.ok(events.every(event=>event.members.includes('buyer') && event.members.includes('seller') && !event.members.includes('other')));
  const trade=await command(buyer,{action:'offer.create',listingId:'listing',requestId:randomUUID(),terms:{kind:'item',itemId:'item'}});
  assert.equal(trade.offer.terms.name,'Pear');
  await assert.rejects(command(buyer,{action:'offer.create',listingId:'listing',requestId:randomUUID(),terms:{kind:'price',amount:-1,currency:'Bells'}}));
 }finally{await db.dropDatabase();await client.close();}
});
